### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by camera-2018** [GoldenSheep402/Hermes#1]
## 主要

- [ ] 发种界面表单
- [ ] 种子促销规则
- [ ] 魔力值系统
- [ ] 等级系统
- [ ] 分享率统计
- [ ] 可分区选择的种子列表
- [ ] 个人信息（头像、做种客户端、做种ip、已完成种子、未完成种子、目前下载、目前做种等）
- [ ] rss 订阅
- [ ] 规则文档
- [ ] 种子收藏
- [ ] 匿名
- [ ] ip地址识别

## 非必要

- [ ] 论坛
- [ ] 邀请树
- [ ] 图床
- [ ] 站内信
- [ ] 排行榜
- [ ] api 令牌（支持第三方用 如PTPP）
- [ ] 种子认领
- [ ] 签到
- [ ] 勋章
- [ ] 种子状态（免费等）变动日志、账户封存日志
- [ ] 公告站（站点下线等公告）
- [ ] 投票
